// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMUxRIZ8PtdwFjfw9GsNzxZhOeDLeZ9Ik',
    appId: '1:1076550807925:web:8e3136471f0eeb3604633c',
    messagingSenderId: '1076550807925',
    projectId: 'tugas-1-f0eb9',
    authDomain: 'tugas-1-f0eb9.firebaseapp.com',
    storageBucket: 'tugas-1-f0eb9.firebasestorage.app',
    measurementId: 'G-V4ZZS17VR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbI7SLn2zYyQ35q_AOgE6en-AlLIB3mD0',
    appId: '1:1076550807925:android:1b9156669220cfb204633c',
    messagingSenderId: '1076550807925',
    projectId: 'tugas-1-f0eb9',
    storageBucket: 'tugas-1-f0eb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdTOSyjnuRPtZHeY0wzbr8c9IT8qZm8-Y',
    appId: '1:1076550807925:ios:9f78b8159d122f4504633c',
    messagingSenderId: '1076550807925',
    projectId: 'tugas-1-f0eb9',
    storageBucket: 'tugas-1-f0eb9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdTOSyjnuRPtZHeY0wzbr8c9IT8qZm8-Y',
    appId: '1:1076550807925:ios:9f78b8159d122f4504633c',
    messagingSenderId: '1076550807925',
    projectId: 'tugas-1-f0eb9',
    storageBucket: 'tugas-1-f0eb9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMUxRIZ8PtdwFjfw9GsNzxZhOeDLeZ9Ik',
    appId: '1:1076550807925:web:ae78624bfcefa61704633c',
    messagingSenderId: '1076550807925',
    projectId: 'tugas-1-f0eb9',
    authDomain: 'tugas-1-f0eb9.firebaseapp.com',
    storageBucket: 'tugas-1-f0eb9.firebasestorage.app',
    measurementId: 'G-SHXHBJHT85',
  );
}
