// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp6GQA9xnIRTakEHZsluXv9MKk7lqFpHg',
    appId: '1:280603210483:web:809b18dd8c6eb3ea143d86',
    messagingSenderId: '280603210483',
    projectId: 'dewi-berliana-brilliant',
    authDomain: 'dewi-berliana-brilliant.firebaseapp.com',
    storageBucket: 'dewi-berliana-brilliant.firebasestorage.app',
    measurementId: 'G-28KZDW4FCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYTgHCnNZXa1il549j-KRO2dtVu-9Izt8',
    appId: '1:280603210483:android:b62166d37ac1d398143d86',
    messagingSenderId: '280603210483',
    projectId: 'dewi-berliana-brilliant',
    storageBucket: 'dewi-berliana-brilliant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALS2hoC4uEif8J5F3thfc9AbKY7Y41BpM',
    appId: '1:280603210483:ios:dffa46db2b25a55c143d86',
    messagingSenderId: '280603210483',
    projectId: 'dewi-berliana-brilliant',
    storageBucket: 'dewi-berliana-brilliant.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALS2hoC4uEif8J5F3thfc9AbKY7Y41BpM',
    appId: '1:280603210483:ios:dffa46db2b25a55c143d86',
    messagingSenderId: '280603210483',
    projectId: 'dewi-berliana-brilliant',
    storageBucket: 'dewi-berliana-brilliant.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp6GQA9xnIRTakEHZsluXv9MKk7lqFpHg',
    appId: '1:280603210483:web:90d2bb36bb6c6e99143d86',
    messagingSenderId: '280603210483',
    projectId: 'dewi-berliana-brilliant',
    authDomain: 'dewi-berliana-brilliant.firebaseapp.com',
    storageBucket: 'dewi-berliana-brilliant.firebasestorage.app',
    measurementId: 'G-Q9J8BPKY2N',
  );

}